"""empty message

Revision ID: b35821163ffb
Revises: 
Create Date: 2023-07-18 20:22:20.213306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35821163ffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_category', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_data_action_current_state'), ['current_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_action_data_category'), ['data_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_action_is_being_processed'), ['is_being_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_action_is_main_complete'), ['is_main_complete'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_action_is_main_complete'))
        batch_op.drop_index(batch_op.f('ix_data_action_is_being_processed'))
        batch_op.drop_index(batch_op.f('ix_data_action_data_category'))
        batch_op.drop_index(batch_op.f('ix_data_action_current_state'))
        batch_op.drop_column('data_category')

    # ### end Alembic commands ###
